#!/usr/bin/env python3
"""One standing, catchable Pokemon apiece for the species we added.

Slime and Metal Slime are left out: they are what the two traders hand over,
and a thing you can be given and also walk up to is worth less than either.
That leaves seven, and seven is exactly what the game has room for - which is
the whole reason this file is interesting.

An object event's graphics id is one byte and the sixteen values above
NUM_OBJ_EVENT_GFX are the dynamic VAR ids, so 239 is the ceiling and vanilla
already uses 238 of it. But six of those are UNUSED_*_DOLL - Natu, Magnemite,
Squirtle, Wooper, Pikachu and Porygon2 - and each is referenced exactly once in
the whole tree, by the pointer table and nothing else. Taking those six and the
one genuinely free slot at 239 gives seven, with no expansion patch and no
widening of anything that stores a graphics id.

The sprites come from the party icons, which are already 32x32 and already
drawn for these species; the top frame of each becomes the overworld picture,
and the icon's own palette becomes the object event palette.

Run after tools/newmons.py, which is what puts the icons there:

    python3 tools/statics.py
    python3 tools/statics.py --check
"""
import argparse, collections, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import render_hoenn as R
import terrain as T
import populate as P

MARK = '// Open Hoenn - tools/statics.py'
SMARK = '@ --- open hoenn: statics generated by tools/statics.py ---'
SMARK_END = '@ --- end open hoenn statics ---'
FLAGS = 'include/constants/flags.h'

# Each one stands where its own line already lives, so finding it is a reward
# for having walked the route rather than a lottery somewhere else. The three
# that only exist by evolution are the exceptions - they are put deeper and
# higher, because being handed one is the point of them.
STATICS = [
    dict(sp='LARVESTA',    dir='larvesta',    slot='UNUSED_NATU_DOLL',
         map='MAP_ROUTE144', dirname='Route144', level=20,
         why='the volcanic route it already lives on'),
    dict(sp='VOLCARONA',   dir='volcarona',   slot='UNUSED_MAGNEMITE_DOLL',
         map='MAP_ROUTE148', dirname='Route148', level=45,
         why='the furthest corner of the new region; 14 levels below its own evolution'),
    dict(sp='WIMPOD',      dir='wimpod',      slot='UNUSED_SQUIRTLE_DOLL',
         map='MAP_ROUTE140', dirname='Route140', level=16,
         why='the shore it already lives on'),
    dict(sp='GOLISOPOD',   dir='golisopod',   slot='UNUSED_WOOPER_DOLL',
         map='MAP_ROUTE147', dirname='Route147', level=35,
         why='a deeper shore, five levels past where WIMPOD evolves'),
    dict(sp='VULPIX_A',    dir='vulpix_a',    slot='UNUSED_PIKACHU_DOLL',
         map='MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM', dirname='ShoalCave_LowTideIceRoom',
         level=28, why='the one genuinely cold room in the game'),
    dict(sp='NINETALES_A', dir='ninetales_a', slot='UNUSED_PORYGON2_DOLL',
         map='MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM', dirname='ShoalCave_LowTideLowerRoom',
         level=40, why='the deepest room of the same cave, five levels past its evolution'),
    dict(sp='KING_SLIME',  dir='king_slime',  slot=None,      # takes the free 239
         map='MAP_ROUTE146', dirname='Route146', level=32,
         why='the route it already rules'),
]

PIC_DIR = 'graphics/object_events/pics/pokemon'
PAL_DIR = 'graphics/object_events/palettes'


def camel(s):
    return ''.join(p.capitalize() for p in s.split('_'))


# --- the pictures ---------------------------------------------------------
def sprites(dry):
    """the top frame of each party icon, and the icon's own palette."""
    from PIL import Image
    done = []
    for s in STATICS:
        src = f'{R.ROOT}/graphics/pokemon/{s["dir"]}/icon.png'
        im = Image.open(src)
        if im.mode != 'P':
            sys.exit(f'{src} is {im.mode}, expected an indexed icon')
        frame = im.crop((0, 0, 32, 32))
        if dry:
            continue
        os.makedirs(f'{R.ROOT}/{PIC_DIR}', exist_ok=True)
        frame.save(f'{R.ROOT}/{PIC_DIR}/{s["dir"]}.png')
        pal = im.getpalette()[:48]
        # .gitattributes marks *.pal eol=crlf, as every other palette here is
        with open(f'{R.ROOT}/{PAL_DIR}/{s["dir"]}.pal', 'w', newline='') as f:
            f.write('JASC-PAL\r\n0100\r\n16\r\n')
            for i in range(16):
                f.write(f'{pal[i*3]} {pal[i*3+1]} {pal[i*3+2]}\r\n')
        done.append(s['dir'])
    return [f'{len(done)} sprites and palettes from the party icons'] if done else []


# --- the seven slots ------------------------------------------------------
def block(text, body, anchor=None, before=False):
    """replace this tool's generated block, or add it."""
    if MARK in text:
        i = text.index(MARK)
        j = text.index('// end ' + MARK[3:], i) + len('// end ' + MARK[3:]) + 1
        text = text[:i] + text[j:]
    chunk = MARK + '\n' + body + '// end ' + MARK[3:] + '\n'
    if anchor is None:
        return text.rstrip('\n') + '\n\n' + chunk
    i = text.index(anchor)
    return text[:i] + chunk + text[i:] if before else \
        text[:i + len(anchor)] + '\n' + chunk + text[i + len(anchor):]


def constants(dry):
    p = f'{R.ROOT}/include/constants/event_objects.h'
    t = open(p).read()
    done = []
    for s in STATICS:
        name = f'OBJ_EVENT_GFX_{s["sp"]}'
        if s['slot']:
            old = f'OBJ_EVENT_GFX_UNUSED_{s["slot"][7:]}'
            if old in t:
                t = re.sub(rf'^#define {re.escape(old)}(\s+)(\d+)$',
                           lambda m: f'#define {name}{" " * max(1, len(m.group(1)) + len(old) - len(name))}{m.group(2)}'
                                     f'  {MARK} (was {old})', t, count=1, flags=re.M)
                done.append(f'{name} takes {old}')
        else:
            if name not in t:
                # 239 is free: no id uses it, and dropping the "+ 1" moves the
                # dynamic VAR ids up to start at 240 exactly as the note there
                # says is safe
                t = t.replace('#define NUM_OBJ_EVENT_GFX                        239',
                              f'#define {name}{" " * 32}239  {MARK}\n'
                              '#define NUM_OBJ_EVENT_GFX                        240', 1)
                t = t.replace('#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)',
                              f'#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX)  {MARK}', 1)
                done.append(f'{name} takes the free 239, VARS start at 240')
    if not dry:
        open(p, 'w').write(t)
    return done


def rename_everywhere(dry):
    """the six dolls are named in four data files; move every mention."""
    done = 0
    files = ['src/data/object_events/object_event_graphics_info_pointers.h',
             'src/data/object_events/object_event_graphics_info.h',
             'src/data/object_events/object_event_pic_tables.h',
             'src/data/object_events/object_event_graphics.h']
    for f in files:
        p = f'{R.ROOT}/{f}'
        t = open(p).read()
        for s in STATICS:
            if not s['slot']:
                continue
            old_c = f'OBJ_EVENT_GFX_UNUSED_{s["slot"][7:]}'
            new_c = f'OBJ_EVENT_GFX_{s["sp"]}'
            old_s = 'Unused' + camel(s['slot'][7:])
            new_s = camel(s['sp'])
            n = t.count(old_c) + t.count(old_s)
            t = t.replace(old_c, new_c).replace(old_s, new_s)
            done += n
        if not dry:
            open(p, 'w').write(t)
    return [f'{done} references moved off the unused dolls'] if done else []


def graphics(dry):
    """point the six renamed entries, and the seventh, at the new pictures.

    The dolls were 16x16; a party icon is 32x32, so the whole info struct is
    rewritten rather than nudged - size, width, height, oam and subsprite table
    all move together, and getting one of them wrong shows up as a quarter of a
    sprite rather than as an error.
    """
    pic = f'{R.ROOT}/src/data/object_events/object_event_graphics.h'
    tbl = f'{R.ROOT}/src/data/object_events/object_event_pic_tables.h'
    inf = f'{R.ROOT}/src/data/object_events/object_event_graphics_info.h'
    ptr = f'{R.ROOT}/src/data/object_events/object_event_graphics_info_pointers.h'
    tp, tt, ti, tr = (open(f).read() for f in (pic, tbl, inf, ptr))

    for s in STATICS:
        n, d = camel(s['sp']), s['dir']
        gfx = (f'const u32 gObjectEventPic_{n}[] = INCGFX_U32('
               f'"{PIC_DIR}/{d}.png", ".4bpp", "-mwidth 4 -mheight 4");')
        pal = (f'const u16 gObjectEventPal_{n}[] = INCGFX_U16('
               f'"{PAL_DIR}/{d}.pal", ".gbapal");')
        # Drop every previous mention first. Appending only when absent looked
        # idempotent and was not: a run that failed later still wrote this
        # file, and the next run appended again.
        tp = '\n'.join(l for l in tp.split('\n')
                       if f'gObjectEventPic_{n}[]' not in l
                       and f'gObjectEventPal_{n}[]' not in l)
        tp = tp.rstrip('\n') + f'\n{MARK}\n{gfx}\n{pal}\n'

        want = (f'static const struct SpriteFrameImage sPicTable_{n}[] = {{\n'
                f'    obj_frame_tiles(gObjectEventPic_{n}),\n}};')
        while True:
            m = re.search(rf'static const struct SpriteFrameImage sPicTable_{n}\[\] = \{{.*?\}};',
                          tt, re.S)
            if not m:
                break
            tt = tt.replace(m.group(0), '', 1)
        tt = tt.rstrip('\n') + f'\n\n{MARK}\n{want}\n'

        body = (f'const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_{n} = {{\n'
                f'    .tileTag = TAG_NONE,\n'
                f'    .paletteTag = OBJ_EVENT_PAL_TAG_{s["sp"]},\n'
                f'    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,\n'
                f'    .size = 512,\n'
                f'    .width = 32,\n'
                f'    .height = 32,\n'
                f'    .paletteSlot = PALSLOT_NPC_4,\n'
                f'    .shadowSize = SHADOW_SIZE_M,\n'
                f'    .inanimate = TRUE,\n'
                f'    .disableReflectionPaletteLoad = TRUE,\n'
                f'    .tracks = TRACKS_NONE,\n'
                f'    .oam = &gObjectEventBaseOam_32x32,\n'
                f'    .subspriteTables = sOamTables_32x32,\n'
                f'    .anims = sAnimTable_Inanimate,\n'
                f'    .images = sPicTable_{n},\n'
                f'    .affineAnims = gDummySpriteAffineAnimTable,\n}};')
        while True:
            m = re.search(rf'const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_{n} = \{{.*?\n\}};',
                          ti, re.S)
            if not m:
                break
            ti = ti.replace(m.group(0), '', 1)
        ti = ti.rstrip('\n') + f'\n\n{MARK}\n{body}\n'

        # the pointer table is included before the structs are defined, so it
        # carries its own externs at the top and a new entry needs one
        ext = f'extern const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_{n};'
        if ext not in tr:
            k = tr.index('extern const struct ObjectEventGraphicsInfo ')
            tr = tr[:k] + ext + f'  {MARK}\n' + tr[k:]
        row = f'    [OBJ_EVENT_GFX_{s["sp"]}] = &gObjectEventGraphicsInfo_{n},'
        if f'[OBJ_EVENT_GFX_{s["sp"]}]' not in tr:
            i = tr.rindex('};', 0, tr.index('gMauvilleOldManGraphicsInfoPointers')
                          if 'gMauvilleOldManGraphicsInfoPointers' in tr else len(tr))
            tr = tr[:i] + row + f'  {MARK}\n' + tr[i:]

    if not dry:
        for f, t in ((pic, tp), (tbl, tt), (inf, ti), (ptr, tr)):
            open(f, 'w').write(t)
    return [f'{len(STATICS)} pictures, pic tables, info structs and pointers']


def palettes(dry):
    """a palette tag and a table row apiece, in src/event_object_movement.c."""
    p = f'{R.ROOT}/src/event_object_movement.c'
    t = open(p).read()
    base = max(int(m, 16) for m in re.findall(r'^#define OBJ_EVENT_PAL_TAG_\w+\s+0x([0-9A-Fa-f]+)$',
                                              t, re.M) if int(m, 16) < 0x2000)
    done = []
    for k, s in enumerate(STATICS):
        tag = f'OBJ_EVENT_PAL_TAG_{s["sp"]}'
        if re.search(rf'^#define {tag}\s', t, re.M):
            continue
        anchor = '#define OBJ_EVENT_PAL_TAG_NONE'
        i = t.index(anchor)
        t = t[:i] + f'#define {tag}{" " * max(1, 42 - len(tag))}0x{base + 1 + k:04X}  {MARK}\n' + t[i:]
        row = f'    {{gObjectEventPal_{camel(s["sp"])},{" " * max(1, 24 - len(camel(s["sp"])))}{tag}}},  {MARK}\n'
        j = t.index('static const struct SpritePalette sObjectEventSpritePalettes[] = {')
        j = t.index('\n', j) + 1
        t = t[:j] + row + t[j:]
        done.append(tag)
    if not dry and done:
        open(p, 'w').write(t)
    return [f'{len(done)} object event palettes'] if done else []


# --- where each one stands ------------------------------------------------
def spot(const, mapdir, taken):
    """the deepest cell of the map that a sprite can stand on without shutting
    anything behind it - the same test tools/populate.py uses for item balls,
    because an object event you have not battled is just as solid."""
    lay, maps, _ = R.solve()
    rend = R.Renderer()
    L, w, h, raw = P.load(const, lay, maps)
    C = T.Classifier(rend, L['primary_tileset'], L.get('secondary_tileset'))
    cls = [C(v & 0x3FF, (v >> 10) & 3) for v in raw]
    live, walk = P.reachable(w, h, raw, cls)
    ele = [(v >> 12) & 0xF for v in raw]
    cut = P.articulations(walk, ele, w, h)
    ok = lambda a, b: a == b or 0 in (a, b) or 15 in (a, b)
    # A route is entered across its edge; a cave room is entered through a
    # warp, and its edges are all wall. Seeding from the rim on an interior map
    # finds nothing reachable at all, so the warps are the way in there.
    seed = [i for i in live if i % w in (0, w-1) or i // w in (0, h-1)]
    if not seed:
        j = json.load(open(f'{R.ROOT}/data/maps/{mapdir}/map.json'))
        live = {i for i, v in enumerate(raw) if ((v >> 10) & 3) == 0}
        seed = [e['y']*w + e['x'] for e in (j.get('warp_events') or [])
                if 0 <= e['x'] < w and 0 <= e['y'] < h]
    dist = {i: 0 for i in seed}
    q = collections.deque(seed)
    while q:
        i = q.popleft()
        x, y = i % w, i // w
        for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
            j = ny*w + nx
            if 0 <= nx < w and 0 <= ny < h and j not in dist and j in live and ok(ele[i], ele[j]):
                dist[j] = dist[i] + 1
                q.append(j)
    for i in sorted(dist, key=lambda i: -dist[i]):
        x, y = i % w, i // w
        if (i in cut or (x, y) in taken or cls[i] in (T.WATER, T.POND)
                or not (1 <= x < w-1 and 1 <= y < h-1)):
            continue
        return x, y, (raw[i] >> 12) & 0xF, dist[i]
    sys.exit(f'nowhere to stand one on {const}')


def hide_flags(dry):
    """one flag per static, claimed the way tools/populate.py claims its own."""
    p = f'{R.ROOT}/{FLAGS}'
    t = open(p).read()
    done = []
    for s in STATICS:
        for kind in ('HIDE', 'CAUGHT'):
            name = f'FLAG_{kind}_STATIC_{s["sp"]}'
            if re.search(rf'^#define {name}\s', t, re.M):
                continue
            m = re.search(r'^#define (FLAG_UNUSED_0x[0-9A-Fa-f]+)\s+'
                          r'(0x[0-9A-Fa-f]+) // Unused Flag$', t, re.M)
            if not m:
                sys.exit('no unused flags left')
            t = t.replace(m.group(0), f'#define {name}'
                          f'{" " * max(1, 60 - len(name))}{m.group(2)} {MARK} ({m.group(1)})', 1)
            done.append(name)
    if not dry and done:
        open(p, 'w').write(t)
    return [f'{len(done)} flags claimed'] if done else []


def scripts_for(s):
    """vanilla's own static-Pokemon shape: cry, battle, and gone if you win."""
    n, m = s['sp'], s['dirname']
    lbl = f'{m}_EventScript_Static{camel(n)}'
    return [f'{lbl}::',
            '\tlock',
            '\tfaceplayer',
            '\twaitse',
            f'\tplaymoncry SPECIES_{n}, CRY_MODE_ENCOUNTER',
            '\tdelay 40',
            '\twaitmoncry',
            f'\tsetwildbattle SPECIES_{n}, {s["level"]}',
            '\tdowildbattle',
            '\tspecialvar VAR_RESULT, GetBattleOutcome',
            f'\tgoto_if_eq VAR_RESULT, B_OUTCOME_WON, {lbl}Gone',
            f'\tgoto_if_eq VAR_RESULT, B_OUTCOME_CAUGHT, {lbl}Gone',
            f'\tgoto_if_eq VAR_RESULT, B_OUTCOME_RAN, {lbl}Fled',
            f'\tgoto_if_eq VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED, {lbl}Fled',
            f'\tsetflag FLAG_CAUGHT_STATIC_{n}',
            '\trelease',
            '\tend',
            '',
            f'{lbl}Gone::',
            f'\tsetflag FLAG_CAUGHT_STATIC_{n}',
            f'\tsetflag FLAG_HIDE_STATIC_{n}',
            '\tgoto Common_EventScript_RemoveStaticPokemon',
            '\tend',
            '',
            f'{lbl}Fled::',
            f'\tsetvar VAR_0x8004, SPECIES_{n}',
            '\tgoto Common_EventScript_LegendaryFlewAway',
            '\tend',
            '']


def place(dry):
    done = []
    per_map = collections.defaultdict(list)
    for s in STATICS:
        per_map[(s['map'], s['dirname'])].append(s)
    for (const, m), group in sorted(per_map.items()):
        q = f'{R.ROOT}/data/maps/{m}/map.json'
        d = json.load(open(q))
        mine = {f'{m}_EventScript_Static{camel(s["sp"])}' for s in group}
        keep = [o for o in (d.get('object_events') or []) if o['script'] not in mine]
        taken = {(o['x'], o['y']) for o in keep}
        for s in group:
            x, y, e, depth = spot(const, m, taken)
            taken.add((x, y))
            keep.append({
                'graphics_id': f'OBJ_EVENT_GFX_{s["sp"]}', 'x': x, 'y': y,
                'elevation': e, 'movement_type': 'MOVEMENT_TYPE_LOOK_AROUND',
                'movement_range_x': 0, 'movement_range_y': 0,
                'trainer_type': 'TRAINER_TYPE_NONE',
                'trainer_sight_or_berry_tree_id': '0',
                'script': f'{m}_EventScript_Static{camel(s["sp"])}',
                'flag': f'FLAG_HIDE_STATIC_{s["sp"]}'})
            done.append(f'{s["sp"]:12s} Lv{s["level"]:<3d} {const[4:]:32s} '
                        f'({x},{y}) {depth} steps in')
        d['object_events'] = keep
        if not dry:
            json.dump(d, open(q, 'w'), indent=2)

        sp = f'{R.ROOT}/data/maps/{m}/scripts.inc'
        src = open(sp).read()
        if SMARK in src:
            src = src[:src.index(SMARK)] + src[src.index(SMARK_END) + len(SMARK_END):]
        body = [SMARK, '']
        for s in group:
            body += scripts_for(s)
        body.append(SMARK_END)
        if not dry:
            open(sp, 'w').write(src.rstrip('\n') + '\n\n' + '\n'.join(body) + '\n')
    return done


def check():
    bad = []
    ev = open(f'{R.ROOT}/include/constants/event_objects.h').read()
    ids = {}
    for s in STATICS:
        m = re.search(rf'^#define OBJ_EVENT_GFX_{s["sp"]}\s+(\d+)', ev, re.M)
        if not m:
            bad.append(f'no OBJ_EVENT_GFX_{s["sp"]}')
            continue
        ids[s['sp']] = int(m.group(1))
    n = re.search(r'^#define NUM_OBJ_EVENT_GFX\s+(\d+)', ev, re.M)
    if n:
        for sp, v in ids.items():
            if v >= int(n.group(1)):
                bad.append(f'OBJ_EVENT_GFX_{sp} is {v}, at or past '
                           f'NUM_OBJ_EVENT_GFX {n.group(1)}')
    if len(set(ids.values())) != len(ids):
        bad.append('two statics share a graphics id')
    # nothing may still refer to the dolls we took
    for s in STATICS:
        if not s['slot']:
            continue
        for f in ('src/data/object_events/object_event_graphics_info_pointers.h',
                  'src/data/object_events/object_event_graphics_info.h',
                  'src/data/object_events/object_event_pic_tables.h',
                  'src/data/object_events/object_event_graphics.h'):
            if f'Unused{camel(s["slot"][7:])}' in open(f'{R.ROOT}/{f}').read():
                bad.append(f'{f} still mentions the {s["slot"]} it gave up')

    from PIL import Image
    for s in STATICS:
        p = f'{R.ROOT}/{PIC_DIR}/{s["dir"]}.png'
        if not os.path.exists(p):
            bad.append(f'missing {p}')
            continue
        im = Image.open(p)
        if im.size != (32, 32):
            bad.append(f'{p} is {im.size}, the info struct says 32x32')
        if not os.path.exists(f'{R.ROOT}/{PAL_DIR}/{s["dir"]}.pal'):
            bad.append(f'missing palette for {s["sp"]}')

    # every static stands somewhere real, and blocks nothing
    lay, maps, _ = R.solve()
    for s in STATICS:
        d = json.load(open(f'{R.ROOT}/data/maps/{s["dirname"]}/map.json'))
        o = [o for o in d['object_events']
             if o['script'].endswith(f'Static{camel(s["sp"])}')]
        if len(o) != 1:
            bad.append(f'{s["sp"]} has {len(o)} object events, want 1')
            continue
        L, w, h, raw = P.load(s['map'], lay, maps)
        v = raw[o[0]['y']*w + o[0]['x']]
        if (v >> 10) & 3:
            bad.append(f'{s["sp"]} stands on an impassable cell')
        src = open(f'{R.ROOT}/data/maps/{s["dirname"]}/scripts.inc').read()
        if o[0]['script'] + '::' not in src:
            bad.append(f'{s["sp"]} points at a script that is not there')
    if not bad:
        print(f'{len(STATICS)} statics: ids {sorted(ids.values())}, all under '
              f'NUM_OBJ_EVENT_GFX, all standing somewhere walkable')
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--dry-run', action='store_true')
    a = ap.parse_args()
    dry = a.dry_run
    for line in (sprites(dry) + constants(dry) + rename_everywhere(dry)
                 + graphics(dry) + palettes(dry) + hide_flags(dry) + place(dry)):
        print(f'  {line}')
    if a.check:
        bad = check()
        if bad:
            sys.exit('\n'.join(bad))


if __name__ == '__main__':
    sys.exit(main())
