#!/usr/bin/env python3
"""Two people in Littleroot who want something you have.

The first will trade you a POKeMON for your starter and will not say what.
That is the whole point of him, so the text never names the species and the
script never buffers it - vanilla's trade dialogue puts the offered species in
STR_VAR_2, and simply not using STR_VAR_2 is what keeps the secret. The trade
scene reveals it, which is after you have agreed, which is where a mystery
belongs.

He needs three entries in sIngameTrades rather than one, because an in-game
trade asks for a fixed species and the starter is one of three. VAR_STARTER_MON
picks which.

The second is Steven, who wants LIQUID ORE - a new item, found in the deepest
corners of the new routes by tools/populate.py - and will hand over a level 1
METAL SLIME for each one. He is a man who collects rare stones and this is the
rarest thing in Hoenn, and neither of them mentions that it is the same
substance the POKeMON is made of.

The item's icon is drawn from METAL SLIME's own palette, for the same reason.

    python3 tools/trades.py            # apply
    python3 tools/trades.py --check    # verify what is written
"""
import argparse, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import render_hoenn as R

MARK = '// Open Hoenn - tools/trades.py'
SMARK = '@ --- open hoenn: trades generated by tools/trades.py ---'
SMARK_END = '@ --- end open hoenn trades ---'

ITEM = 'ITEM_LIQUID_ORE'
ITEM_NAME = 'LIQUID ORE'
ITEM_DESC = ('A bead of strange\\n'
             'ore. It is heavy,\\n'
             'and it moves.')
ICON = 'graphics/items/icons/liquid_ore.png'
PAL = 'graphics/items/icon_palettes/liquid_ore.pal'

# where the two of them stand. Littleroot's open grass, clear of the doors, the
# signs and each other; check() proves both cells are walkable and that neither
# is the only way through to anywhere.
TRADER_AT = (4, 12)
STEVEN_AT = (14, 12)

TRADES = [                       # (constant, starter species, VAR_STARTER_MON)
    ('INGAME_TRADE_SLIME_TREECKO', 'SPECIES_TREECKO', 0),
    ('INGAME_TRADE_SLIME_TORCHIC', 'SPECIES_TORCHIC', 1),
    ('INGAME_TRADE_SLIME_MUDKIP',  'SPECIES_MUDKIP',  2),
]


# --- the item -------------------------------------------------------------
def metal_slime_palette():
    """the greys METAL SLIME is drawn in, lightest first.

    Its palette also carries two rust entries at 8 and 9, left over from the
    basic slime; the sprite no longer uses them and neither does this.
    """
    from PIL import Image
    im = Image.open(f'{R.ROOT}/graphics/pokemon/metal_slime/front.png')
    p = im.getpalette()[:16*3]
    cols = [tuple(p[i*3:i*3+3]) for i in range(16)]
    return [cols[i] for i in (1, 2, 4, 5, 6, 7, 10, 12, 14, 15)]


def draw_icon():
    """a 24x24 bead of the stuff, lit from the top left.

    Item icons are 24x24 and 4bpp, and the .pal beside them is what the game
    actually loads - the PNG's own palette only has to agree with it, index for
    index, or gbagfx writes the right shape in the wrong colours.
    """
    from PIL import Image
    ramp = metal_slime_palette()
    pal = [(0, 0, 0)] + ramp + [(0, 0, 0)] * (16 - 1 - len(ramp))

    W = 24
    px = [[0] * W for _ in range(W)]
    DARK = len(ramp)                # the last ramp entry, used as the outline
    BODY = len(ramp) - 2            # how many shades the body gets

    def blob(cx, cy, rx, ry, lift):
        """a lit ellipse, painted body-first so the outline can go round it."""
        inside = set()
        for y in range(W):
            for x in range(W):
                dx, dy = (x - cx) / rx, (y - cy) / ry
                if dx*dx + dy*dy <= 1.0:
                    inside.add((x, y))
        for x, y in inside:
            # distance from a light source up and left of the blob, which is
            # where every item icon in this game is lit from
            lx, ly = (x - (cx - rx*0.42)) / rx, (y - (cy - ry*0.46)) / ry
            band = min(BODY - 1, max(0, int((lx*lx + ly*ly) * BODY * 0.85)))
            px[y][x] = 1 + band + lift
        # the outline: every cell touching the blob from outside
        for x, y in list(inside):
            for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
                if (0 <= nx < W and 0 <= ny < W and (nx, ny) not in inside):
                    px[ny][nx] = DARK
        return inside

    blob(11.0, 15.0, 6.8, 5.0, 0)
    # Two beads adrift above it, the way METAL SLIME is drawn - well clear of
    # the bead and of each other, and different sizes. Sitting them level and
    # symmetrical either side made the whole icon read as a face with ears.
    blob(18.0, 4.0, 2.1, 2.1, 1)
    blob(4.5, 7.0, 1.3, 1.3, 1)

    # the specular, which is what makes it read as metal rather than as a rock
    for y, x in ((12, 7), (12, 8), (11, 8), (13, 7)):
        px[y][x] = 1

    im = Image.new('P', (W, W))
    flat = []
    for c in pal:
        flat += list(c)
    im.putpalette(flat + [0] * (768 - len(flat)))
    im.putdata([px[y][x] for y in range(W) for x in range(W)])
    return im, pal


def write_icon(dry):
    im, pal = draw_icon()
    if dry:
        return
    os.makedirs(os.path.dirname(f'{R.ROOT}/{ICON}'), exist_ok=True)
    im.save(f'{R.ROOT}/{ICON}')
    with open(f'{R.ROOT}/{PAL}', 'w') as f:
        f.write('JASC-PAL\n0100\n16\n')
        for c in pal:
            f.write(f'{c[0]} {c[1]} {c[2]}\n')


def add_item(dry):
    """the constant, the table row, the icon, and the two declarations."""
    done = []

    p = f'{R.ROOT}/include/constants/items.h'
    text = open(p).read()
    if ITEM not in text:
        m = re.search(r'^#define ITEMS_COUNT (\d+)$', text, re.M)
        n = int(m.group(1))
        pad = ' ' * max(1, 33 - len(ITEM))
        text = text.replace(
            m.group(0),
            f'\n// Open Hoenn - tools/trades.py\n'
            f'#define {ITEM}{pad}{n}\n\n#define ITEMS_COUNT {n + 1}', 1)
        done.append(f'{ITEM} = {n}, ITEMS_COUNT {n} -> {n + 1}')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/text/item_descriptions.h'
    text = open(p).read()
    if 'sLiquidOreDesc' not in text:
        text = text.rstrip('\n') + (
            f'\n\n{MARK}\nstatic const u8 sLiquidOreDesc[] = _(\n'
            f'    "{ITEM_DESC}");\n')
        done.append('description')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/items.h'
    text = open(p).read()
    if f'[{ITEM}]' not in text:
        row = (f'    {MARK}\n'
               f'    [{ITEM}] =\n'
               f'    {{\n'
               f'        .name = _("{ITEM_NAME}"),\n'
               f'        .itemId = {ITEM},\n'
               f'        .price = 0,\n'
               f'        .description = sLiquidOreDesc,\n'
               f'        .pocket = POCKET_ITEMS,\n'
               f'        .type = ITEM_USE_BAG_MENU,\n'
               f'        .fieldUseFunc = ItemUseOutOfBattle_CannotUse,\n'
               f'    }},\n')
        i = text.rindex('};')
        text = text[:i] + row + text[i:]
        done.append('gItems row')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/graphics/items.h'
    text = open(p).read()
    if 'gItemIcon_LiquidOre' not in text:
        text = text.rstrip('\n') + (
            f'\n\n{MARK}\n'
            f'const u32 gItemIcon_LiquidOre[] = INCGFX_U32("{ICON}", ".4bpp.lz");\n'
            f'const u32 gItemIconPalette_LiquidOre[] = '
            f'INCGFX_U32("{PAL}", ".gbapal.lz");\n')
        done.append('graphics')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/include/graphics.h'
    text = open(p).read()
    if 'gItemIcon_LiquidOre' not in text:
        anchor = 'extern const u32 gItemIcon_Nugget[];'
        text = text.replace(anchor, anchor + f'\n{MARK}\n'
                            'extern const u32 gItemIcon_LiquidOre[];\n'
                            'extern const u32 gItemIconPalette_LiquidOre[];', 1)
        done.append('externs')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/item_icon_table.h'
    text = open(p).read()
    if f'[{ITEM}]' not in text:
        # before the return-to-field arrow, which is indexed at ITEMS_COUNT and
        # so has to stay last
        anchor = '    // Return to field arrow'
        text = text.replace(anchor, f'    {MARK}\n    [{ITEM}] = '
                            '{gItemIcon_LiquidOre, gItemIconPalette_LiquidOre},\n'
                            + anchor, 1)
        done.append('icon table')
        if not dry:
            open(p, 'w').write(text)

    write_icon(dry)
    return done


# --- the one flag this needs ----------------------------------------------
FLAG = 'FLAG_LITTLEROOT_SLIME_TRADED'
FLAGS = 'include/constants/flags.h'


def add_flag(dry):
    """rename one FLAG_UNUSED, the way tools/populate.py claims its own.

    The old name stays in the comment so a re-run finds the flag it already
    took instead of walking further down the pool every time, and so the two
    tools cannot end up on the same bit: populate.py only reads lines still
    labelled "Unused Flag", and only hands back the ones carrying its mark.
    """
    p = f'{R.ROOT}/{FLAGS}'
    text = open(p).read()
    if re.search(r'^#define ' + FLAG + r'\s', text, re.M):
        return []
    m = re.search(r'^#define (FLAG_UNUSED_0x[0-9A-Fa-f]+)\s+'
                  r'(0x[0-9A-Fa-f]+) // Unused Flag$', text, re.M)
    if not m:
        sys.exit('no unused flags left')
    pad = ' ' * max(1, 60 - len(FLAG))
    text = text.replace(m.group(0),
                        f'#define {FLAG}{pad}{m.group(2)} {MARK} ({m.group(1)})', 1)
    if not dry:
        open(p, 'w').write(text)
    return [f'{FLAG} = {m.group(2)} (was {m.group(1)})']


# --- the three trades -----------------------------------------------------
def add_trades(dry):
    done = []
    p = f'{R.ROOT}/include/constants/trade.h'
    text = open(p).read()
    if TRADES[0][0] not in text:
        m = re.search(r'^#define INGAME_TRADE_MEOWTH (\d+)$', text, re.M)
        n = int(m.group(1))
        add = '\n'.join(f'#define {c} {n + 1 + k}'
                        for k, (c, _, _) in enumerate(TRADES))
        text = text.replace(m.group(0), m.group(0) + f'\n{MARK}\n' + add, 1)
        done.append(f'{len(TRADES)} trade ids from {n + 1}')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/trade.h'
    text = open(p).read()
    if TRADES[0][0] not in text:
        rows = ''
        for const, starter, _ in TRADES:
            rows += (
                f'    [{const}] =\n'
                f'    {{\n'
                f'        .nickname = _("?"),\n'
                f'        .species = SPECIES_SLIME,\n'
                f'        .ivs = {{15, 15, 15, 15, 15, 15}},\n'
                f'        .abilityNum = 0,\n'
                f'        .otId = 51337,\n'
                f'        .conditions = {{5, 5, 5, 5, 5}},\n'
                f'        .personality = 0x2D,\n'
                f'        .heldItem = ITEM_NONE,\n'
                f'        .mailNum = -1,\n'
                f'        .otName = _("?"),\n'
                f'        .otGender = MALE,\n'
                f'        .sheen = 10,\n'
                f'        .requestedSpecies = {starter}\n'
                f'    }},\n')
        i = text.index('static const struct InGameTrade sIngameTrades[]')
        j = text.index('\n};', i)
        # vanilla's last entry has no trailing comma, being last
        text = text[:j] + ',\n' + f'    {MARK}\n' + rows + text[j + 1:]
        done.append('sIngameTrades rows')
        if not dry:
            open(p, 'w').write(text)
    return done


# --- the two of them ------------------------------------------------------
NAME = 'LittlerootTown'


def scripts():
    S = [SMARK, '']
    # The trader. VAR_0x8008 is which trade, and it has to be set before
    # GetInGameTradeSpeciesInfo, which reads it through VAR_0x8004.
    S += [f'{NAME}_EventScript_SlimeTrader::',
          '\tlock',
          '\tfaceplayer',
          f'\tgoto_if_unset FLAG_SYS_POKEMON_GET, {NAME}_EventScript_SlimeTraderNoMon',
          f'\tgoto_if_set FLAG_LITTLEROOT_SLIME_TRADED, {NAME}_EventScript_SlimeTraderDone',
          f'\tcall {NAME}_EventScript_SlimeTraderPick',
          '\tcopyvar VAR_0x8004, VAR_0x8008',
          '\tspecialvar VAR_RESULT, GetInGameTradeSpeciesInfo',
          '\tcopyvar VAR_0x8009, VAR_RESULT',
          f'\tmsgbox {NAME}_Text_SlimeTraderOffer, MSGBOX_YESNO',
          f'\tgoto_if_eq VAR_RESULT, NO, {NAME}_EventScript_SlimeTraderDecline',
          '\tspecial ChoosePartyMon',
          '\tcopyvar VAR_0x800A, VAR_0x8004',
          f'\tgoto_if_eq VAR_0x8004, PARTY_NOTHING_CHOSEN, {NAME}_EventScript_SlimeTraderDecline',
          '\tcopyvar VAR_0x8005, VAR_0x800A',
          '\tspecialvar VAR_RESULT, GetTradeSpecies',
          f'\tgoto_if_ne VAR_RESULT, VAR_0x8009, {NAME}_EventScript_SlimeTraderWrongMon',
          '\tcopyvar VAR_0x8004, VAR_0x8008',
          '\tcopyvar VAR_0x8005, VAR_0x800A',
          '\tspecial CreateInGameTradePokemon',
          '\tspecial DoInGameTradeScene',
          f'\tmsgbox {NAME}_Text_SlimeTraderAfter, MSGBOX_DEFAULT',
          '\tsetflag FLAG_LITTLEROOT_SLIME_TRADED',
          '\trelease',
          '\tend',
          '']
    # which of the three, by starter
    S += [f'{NAME}_EventScript_SlimeTraderPick::']
    for const, _, val in TRADES:
        S.append(f'\tgoto_if_eq VAR_STARTER_MON, {val}, '
                 f'{NAME}_EventScript_SlimeTraderPick{val}')
    S += ['\tsetvar VAR_0x8008, ' + TRADES[0][0], '\treturn', '']
    for const, _, val in TRADES:
        S += [f'{NAME}_EventScript_SlimeTraderPick{val}::',
              f'\tsetvar VAR_0x8008, {const}', '\treturn', '']

    S += [f'{NAME}_EventScript_SlimeTraderNoMon::',
          f'\tmsgbox {NAME}_Text_SlimeTraderNoMon, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_SlimeTraderDecline::',
          f'\tmsgbox {NAME}_Text_SlimeTraderDecline, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_SlimeTraderWrongMon::',
          '\tbufferspeciesname STR_VAR_1, VAR_0x8009',
          f'\tmsgbox {NAME}_Text_SlimeTraderWrongMon, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_SlimeTraderDone::',
          f'\tmsgbox {NAME}_Text_SlimeTraderDone, MSGBOX_DEFAULT',
          '\trelease', '\tend', '']

    # Steven. Repeatable: one ore in, one METAL SLIME out, as often as you
    # like, because the ore is what is rare and not the trade.
    S += [f'{NAME}_EventScript_Steven::',
          '\tlock',
          '\tfaceplayer',
          f'\tcheckitem {ITEM}, 1',
          f'\tgoto_if_eq VAR_RESULT, FALSE, {NAME}_EventScript_StevenNoOre',
          f'\tmsgbox {NAME}_Text_StevenOffer, MSGBOX_YESNO',
          f'\tgoto_if_eq VAR_RESULT, NO, {NAME}_EventScript_StevenDecline',
          '\tgetpartysize',
          f'\tgoto_if_eq VAR_RESULT, PARTY_SIZE, {NAME}_EventScript_StevenPartyFull',
          f'\tremoveitem {ITEM}, 1',
          '\tgivemon SPECIES_METAL_SLIME, 1, ITEM_NONE',
          '\tplayfanfare MUS_OBTAIN_ITEM',
          '\twaitfanfare',
          f'\tmsgbox {NAME}_Text_StevenAfter, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_StevenNoOre::',
          f'\tmsgbox {NAME}_Text_StevenNoOre, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_StevenDecline::',
          f'\tmsgbox {NAME}_Text_StevenDecline, MSGBOX_DEFAULT',
          '\trelease', '\tend', '',
          f'{NAME}_EventScript_StevenPartyFull::',
          f'\tmsgbox {NAME}_Text_StevenPartyFull, MSGBOX_DEFAULT',
          '\trelease', '\tend', '']

    def text(label, *lines):
        S.append(f'{NAME}_Text_{label}:')
        for i, l in enumerate(lines):
            end = '$' if i == len(lines) - 1 else ''
            S.append(f'\t.string "{l}{end}"')
        S.append('')

    # Nothing here names the species, and nothing buffers STR_VAR_2.
    text('SlimeTraderOffer',
         'I have something here I am willing\\n',
         'to part with.\\p',
         'What is it? Ah. I would rather not\\n',
         'say. It is easier if you simply see.\\p',
         'Your {STR_VAR_1}, then, for mine.\\n',
         'Do we have an arrangement?')
    text('SlimeTraderAfter',
         'There. No refunds, no returns, and\\n',
         'no explanations.\\p',
         'Feed it. It does eat.')
    text('SlimeTraderNoMon',
         'You have nothing to trade with, and\\n',
         'I have nothing to say to you.')
    text('SlimeTraderDecline',
         'A shame. It will keep.')
    text('SlimeTraderWrongMon',
         'No. Your {STR_VAR_1}, or nothing.\\n',
         'I am particular.')
    text('SlimeTraderDone',
         'We are square, you and I.\\p',
         'How is it settling in?')
    text('StevenOffer',
         'Excuse me - that ore in your bag.\\n',
         'May I see it?\\p',
         'Extraordinary. It has a shine no\\n',
         'mineral of this region should have,\\l',
         'and it is warm, which stone is not.\\p',
         'I would very much like it. In return,\\n',
         'a POKéMON I found in the same rock.\\p',
         'Would you trade?')
    text('StevenAfter',
         'Take good care of it. It is young.\\p',
         'Curious, is it not, that the ore and\\n',
         'the POKéMON weigh exactly the same?\\p',
         'I have been trying not to think\\n',
         'about that.')
    text('StevenNoOre',
         'Steven. I collect rare stones.\\p',
         'There is an ore in the far corners\\n',
         'of the new routes - heavy, bright,\\l',
         'and it will not sit still.\\p',
         'Bring me one and I will make it\\n',
         'worth the walk.')
    text('StevenDecline',
         'Of course. Think it over.')
    text('StevenPartyFull',
         'Your team is full. I would rather it\\n',
         'went straight into your care.')
    S.append(SMARK_END)
    return S


def add_npcs(dry):
    import json
    done = []
    p = f'{R.ROOT}/data/maps/{NAME}/scripts.inc'
    src = open(p).read()
    if SMARK in src:
        src = src[:src.index(SMARK)] + src[src.index(SMARK_END) + len(SMARK_END):]
    # before the gate block, which tools/newmaps.py cuts at its own marker and
    # rewrites; anything sitting inside that cut would be taken with it
    gate = '@ --- open hoenn: gates generated by tools/newmaps.py ---'
    body = '\n'.join(scripts()) + '\n'
    if gate in src:
        i = src.index(gate)
        src = src[:i] + body + '\n' + src[i:]
    else:
        src = src.rstrip('\n') + '\n\n' + body
    done.append('scripts')
    if not dry:
        open(p, 'w').write(src)

    p = f'{R.ROOT}/data/maps/{NAME}/map.json'
    d = json.load(open(p))
    keep = [o for o in d['object_events']
            if o['script'] not in (f'{NAME}_EventScript_SlimeTrader',
                                   f'{NAME}_EventScript_Steven')]
    for (x, y), gfx, script, look in (
            (TRADER_AT, 'OBJ_EVENT_GFX_MAN_3',
             f'{NAME}_EventScript_SlimeTrader', 'MOVEMENT_TYPE_FACE_DOWN'),
            (STEVEN_AT, 'OBJ_EVENT_GFX_STEVEN',
             f'{NAME}_EventScript_Steven', 'MOVEMENT_TYPE_FACE_DOWN')):
        keep.append({
            'graphics_id': gfx, 'x': x, 'y': y, 'elevation': 3,
            'movement_type': look, 'movement_range_x': 0, 'movement_range_y': 0,
            'trainer_type': 'TRAINER_TYPE_NONE',
            'trainer_sight_or_berry_tree_id': '0',
            'script': script, 'flag': '0'})
    d['object_events'] = keep
    done.append(f'2 object events at {TRADER_AT} and {STEVEN_AT}')
    if not dry:
        json.dump(d, open(p, 'w'), indent=2)
    return done


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--dry-run', action='store_true')
    a = ap.parse_args()

    for what in (add_item(a.dry_run), add_flag(a.dry_run),
                 add_trades(a.dry_run), add_npcs(a.dry_run)):
        for line in what:
            print(f'  + {line}')

    if a.check:
        bad = check()
        if bad:
            sys.exit('\n'.join(bad))
        print('checks pass')


def check():
    import json, struct
    bad = []
    items = open(f'{R.ROOT}/include/constants/items.h').read()
    m = re.search(r'^#define ' + ITEM + r'\s+(\d+)$', items, re.M)
    n = re.search(r'^#define ITEMS_COUNT (\d+)$', items, re.M)
    if not m or not n:
        bad.append('item constant or ITEMS_COUNT missing')
    elif int(n.group(1)) != int(m.group(1)) + 1:
        bad.append(f'ITEMS_COUNT {n.group(1)} does not follow {ITEM} {m.group(1)}')
    tbl = open(f'{R.ROOT}/src/data/item_icon_table.h').read()
    if f'[{ITEM}]' not in tbl:
        bad.append('no icon table entry')
    if tbl.index(f'[{ITEM}]') > tbl.index('[ITEMS_COUNT]'):
        bad.append('icon entry is after the return-to-field arrow')
    for p in (ICON, PAL):
        if not os.path.exists(f'{R.ROOT}/{p}'):
            bad.append(f'{p} not written')
    if os.path.exists(f'{R.ROOT}/{ICON}'):
        from PIL import Image
        im = Image.open(f'{R.ROOT}/{ICON}')
        if im.size != (24, 24) or im.mode != 'P':
            bad.append(f'icon is {im.size} {im.mode}, want (24, 24) P')
        pal = open(f'{R.ROOT}/{PAL}').read().split('\n')
        want = [tuple(int(v) for v in l.split()) for l in pal[3:19]]
        got = im.getpalette()[:48]
        for i in range(16):
            if want[i] != tuple(got[i*3:i*3+3]):
                bad.append(f'icon palette {i} is {got[i*3:i*3+3]}, .pal says {want[i]}')
                break

    trades = open(f'{R.ROOT}/src/data/trade.h').read()
    for const, starter, _ in TRADES:
        i = trades.find(f'[{const}] =')
        if i < 0:
            bad.append(f'{const} has no row')
            continue
        blk = trades[i:trades.index('\n    },', i)]
        if f'.requestedSpecies = {starter}' not in blk:
            bad.append(f'{const} does not ask for {starter}')
        if '.species = SPECIES_SLIME' not in blk:
            bad.append(f'{const} does not offer SPECIES_SLIME')

    # the secret: no text in the generated block may name what is offered, and
    # nothing may buffer STR_VAR_2, which GetInGameTradeSpeciesInfo fills with
    # the offered species name
    src = open(f'{R.ROOT}/data/maps/{NAME}/scripts.inc').read()
    blk = src[src.index(SMARK):src.index(SMARK_END)]
    # only what the player reads. Label names are allowed to say SLIME; the
    # dialogue is not, and neither is STR_VAR_2, which
    # GetInGameTradeSpeciesInfo fills with the offered species' name.
    said = '\n'.join(re.findall(r'^\t\.string "(.*)"$', blk, re.M))
    trader = said[:said.index('Steven')] if 'Steven' in said else said
    for leak in ('STR_VAR_2', 'SLIME', 'Slime', 'slime'):
        if leak in trader:
            bad.append(f"the trader says {leak!r}, which gives it away")
    if 'FLAG_' + FLAG[5:] not in blk:
        bad.append('the trade is not flagged, so it would repeat')
    if 'MOVEMENT_TYPE' in blk:
        bad.append('movement belongs in the map, not the script block')

    # both of them stand somewhere real, and neither blocks the only way past
    d = json.load(open(f'{R.ROOT}/data/maps/{NAME}/map.json'))
    lay, maps, _ = R.solve()
    L = lay[maps['MAP_LITTLEROOT_TOWN']['layout']]
    w, h = L['width'], L['height']
    raw = struct.unpack(f'<{w*h}H',
                        open(f'{R.ROOT}/{L["blockdata_filepath"]}', 'rb').read()[:w*h*2])
    walk = [((v >> 10) & 3) == 0 for v in raw]
    ele = [(v >> 12) & 0xF for v in raw]
    solid = {(o['x'], o['y']) for o in d['object_events']}
    for x, y in (TRADER_AT, STEVEN_AT):
        if not walk[y*w + x]:
            bad.append(f'({x},{y}) is not somewhere a person can stand')
    # with every sprite treated as a wall, can the player still get everywhere?
    ok = lambda a, b: a == b or 0 in (a, b) or 15 in (a, b)
    free = [i for i in range(w*h) if walk[i] and (i % w, i // w) not in solid]
    if free:
        seen, q = {free[0]}, [free[0]]
        while q:
            i = q.pop()
            x, y = i % w, i // w
            for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
                j = ny*w + nx
                if (0 <= nx < w and 0 <= ny < h and j not in seen and walk[j]
                        and (nx, ny) not in solid and ok(ele[i], ele[j])):
                    seen.add(j)
                    q.append(j)
        stranded = len(free) - len(seen)
        if stranded:
            bad.append(f'{stranded} cells of Littleroot are cut off by a sprite')
    return bad


if __name__ == '__main__':
    sys.exit(main())
