#!/usr/bin/env python3
"""Two people in Littleroot who want something you have.

The first will trade you a POKeMON for your starter and will not say what.
That is the whole point of him, so the text never names the species and the
script never buffers it - vanilla's trade dialogue puts the offered species in
STR_VAR_2, and simply not using STR_VAR_2 is what keeps the secret. The trade
scene reveals it, which is after you have agreed, which is where a mystery
belongs.

He needs three entries in sIngameTrades rather than one, because an in-game
trade asks for a fixed species and the starter is one of three. VAR_STARTER_MON
picks which.

The second is Steven, who wants LIQUID ORE - a new item, found in the deepest
corners of the new routes by tools/populate.py - and will hand over a level 1
METAL SLIME for each one. He is a man who collects rare stones and this is the
rarest thing in Hoenn, and neither of them mentions that it is the same
substance the POKeMON is made of.

The item's icon is drawn from METAL SLIME's own palette, for the same reason.

    python3 tools/trades.py            # apply
    python3 tools/trades.py --check    # verify what is written
"""
import argparse, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import render_hoenn as R

MARK = '// Open Hoenn - tools/trades.py'
SMARK = '@ --- open hoenn: trades generated by tools/trades.py ---'
SMARK_END = '@ --- end open hoenn trades ---'
HOOK = '@ open hoenn'      # tags lines spliced into a vanilla script

ITEM = 'ITEM_LIQUID_ORE'
ITEM_NAME = 'LIQUID ORE'
ITEM_DESC = ('A bead of strange\\n'
             'ore. It is heavy,\\n'
             'and it moves.')
ICON = 'graphics/items/icons/liquid_ore.png'
PAL = 'graphics/items/icon_palettes/liquid_ore.pal'

# The trader stands in Littleroot's open grass, clear of the doors and the
# signs; check() proves the cell is walkable and that he is not the only way
# through to anywhere.
TRADER_MAP = 'LittlerootTown'
TRADER_AT = (4, 12)

# Steven stands where he already stands: the dead end at the bottom of Granite
# Cave, on the exact tile he leaves from once the letter is delivered. It is
# behind Flash and a cave, which is the point of it.
#
# Vanilla only removeobject's him, and never sets the hide flag it gave him -
# FLAG_HIDE_GRANITE_CAVE_STEVEN exists and is written by nothing in the game -
# so he is back the next time the room loads. Two Stevens on one tile is not
# what anybody wants, so the on-transition script below drives both flags off
# FLAG_DELIVERED_STEVEN_LETTER: the one who wanted the letter is hidden for
# good once he has it, and the one who wants the ore appears in his place.
STEVEN_MAP = 'GraniteCave_StevensRoom'
STEVEN_AT = (7, 8)

# What he hands over. Personality is doing three jobs at once in Gen 3 and all
# three are pinned here: nature is personality % 25, which must land on one of
# the five that change nothing; shininess is GET_SHINY_VALUE(otId, personality)
# against a fixed otId, so it is decided at build time and not by luck; and the
# ability index is personality & 1, which SLIME does not use because it has
# only one ability. check() recomputes the first two rather than trusting this
# comment.
NICKNAME = 'SLIME'
OT_NAME = 'MONTY'
OT_ID = 51337
PERSONALITY = 12                 # 12 % 25 = NATURE_SERIOUS
NEUTRAL = (0, 6, 12, 18, 24)     # HARDY, DOCILE, SERIOUS, BASHFUL, QUIRKY

TRADES = [                       # (constant, starter species, VAR_STARTER_MON)
    ('INGAME_TRADE_SLIME_TREECKO', 'SPECIES_TREECKO', 0),
    ('INGAME_TRADE_SLIME_TORCHIC', 'SPECIES_TORCHIC', 1),
    ('INGAME_TRADE_SLIME_MUDKIP',  'SPECIES_MUDKIP',  2),
]


# --- the item -------------------------------------------------------------
def metal_slime_palette():
    """the greys METAL SLIME is drawn in, lightest first.

    Its palette also carries two rust entries at 8 and 9, left over from the
    basic slime; the sprite no longer uses them and neither does this.
    """
    from PIL import Image
    im = Image.open(f'{R.ROOT}/graphics/pokemon/metal_slime/front.png')
    p = im.getpalette()[:16*3]
    cols = [tuple(p[i*3:i*3+3]) for i in range(16)]
    return [cols[i] for i in (1, 2, 4, 5, 6, 7, 10, 12, 14, 15)]


def draw_icon():
    """a 24x24 bead of the stuff, lit from the top left.

    Item icons are 24x24 and 4bpp, and the .pal beside them is what the game
    actually loads - the PNG's own palette only has to agree with it, index for
    index, or gbagfx writes the right shape in the wrong colours.
    """
    from PIL import Image
    ramp = metal_slime_palette()
    pal = [(0, 0, 0)] + ramp + [(0, 0, 0)] * (16 - 1 - len(ramp))

    W = 24
    px = [[0] * W for _ in range(W)]
    DARK = len(ramp)                # the last ramp entry, used as the outline
    BODY = len(ramp) - 2            # how many shades the body gets

    def blob(cx, cy, rx, ry, lift):
        """a lit ellipse, painted body-first so the outline can go round it."""
        inside = set()
        for y in range(W):
            for x in range(W):
                dx, dy = (x - cx) / rx, (y - cy) / ry
                if dx*dx + dy*dy <= 1.0:
                    inside.add((x, y))
        for x, y in inside:
            # distance from a light source up and left of the blob, which is
            # where every item icon in this game is lit from
            lx, ly = (x - (cx - rx*0.42)) / rx, (y - (cy - ry*0.46)) / ry
            band = min(BODY - 1, max(0, int((lx*lx + ly*ly) * BODY * 0.85)))
            px[y][x] = 1 + band + lift
        # the outline: every cell touching the blob from outside
        for x, y in list(inside):
            for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
                if (0 <= nx < W and 0 <= ny < W and (nx, ny) not in inside):
                    px[ny][nx] = DARK
        return inside

    blob(11.0, 15.0, 6.8, 5.0, 0)
    # Two beads adrift above it, the way METAL SLIME is drawn - well clear of
    # the bead and of each other, and different sizes. Sitting them level and
    # symmetrical either side made the whole icon read as a face with ears.
    blob(18.0, 4.0, 2.1, 2.1, 1)
    blob(4.5, 7.0, 1.3, 1.3, 1)

    # the specular, which is what makes it read as metal rather than as a rock
    for y, x in ((12, 7), (12, 8), (11, 8), (13, 7)):
        px[y][x] = 1

    im = Image.new('P', (W, W))
    flat = []
    for c in pal:
        flat += list(c)
    im.putpalette(flat + [0] * (768 - len(flat)))
    im.putdata([px[y][x] for y in range(W) for x in range(W)])
    return im, pal


def write_icon(dry):
    im, pal = draw_icon()
    if dry:
        return
    os.makedirs(os.path.dirname(f'{R.ROOT}/{ICON}'), exist_ok=True)
    im.save(f'{R.ROOT}/{ICON}')
    # .gitattributes marks *.pal as eol=crlf, and every other palette in the
    # tree is written that way; newline='' keeps Python from undoing it
    with open(f'{R.ROOT}/{PAL}', 'w', newline='') as f:
        f.write('JASC-PAL\r\n0100\r\n16\r\n')
        for c in pal:
            f.write(f'{c[0]} {c[1]} {c[2]}\r\n')


def add_item(dry):
    """the constant, the table row, the icon, and the two declarations."""
    done = []

    p = f'{R.ROOT}/include/constants/items.h'
    text = open(p).read()
    if ITEM not in text:
        m = re.search(r'^#define ITEMS_COUNT (\d+)$', text, re.M)
        n = int(m.group(1))
        pad = ' ' * max(1, 33 - len(ITEM))
        text = text.replace(
            m.group(0),
            f'\n// Open Hoenn - tools/trades.py\n'
            f'#define {ITEM}{pad}{n}\n\n#define ITEMS_COUNT {n + 1}', 1)
        done.append(f'{ITEM} = {n}, ITEMS_COUNT {n} -> {n + 1}')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/text/item_descriptions.h'
    text = open(p).read()
    if 'sLiquidOreDesc' not in text:
        text = text.rstrip('\n') + (
            f'\n\n{MARK}\nstatic const u8 sLiquidOreDesc[] = _(\n'
            f'    "{ITEM_DESC}");\n')
        done.append('description')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/items.h'
    text = open(p).read()
    if f'[{ITEM}]' not in text:
        row = (f'    {MARK}\n'
               f'    [{ITEM}] =\n'
               f'    {{\n'
               f'        .name = _("{ITEM_NAME}"),\n'
               f'        .itemId = {ITEM},\n'
               f'        .price = 0,\n'
               f'        .description = sLiquidOreDesc,\n'
               f'        .pocket = POCKET_ITEMS,\n'
               f'        .type = ITEM_USE_BAG_MENU,\n'
               f'        .fieldUseFunc = ItemUseOutOfBattle_CannotUse,\n'
               f'    }},\n')
        i = text.rindex('};')
        text = text[:i] + row + text[i:]
        done.append('gItems row')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/graphics/items.h'
    text = open(p).read()
    if 'gItemIcon_LiquidOre' not in text:
        text = text.rstrip('\n') + (
            f'\n\n{MARK}\n'
            f'const u32 gItemIcon_LiquidOre[] = INCGFX_U32("{ICON}", ".4bpp.lz");\n'
            f'const u32 gItemIconPalette_LiquidOre[] = '
            f'INCGFX_U32("{PAL}", ".gbapal.lz");\n')
        done.append('graphics')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/include/graphics.h'
    text = open(p).read()
    if 'gItemIcon_LiquidOre' not in text:
        anchor = 'extern const u32 gItemIcon_Nugget[];'
        text = text.replace(anchor, anchor + f'\n{MARK}\n'
                            'extern const u32 gItemIcon_LiquidOre[];\n'
                            'extern const u32 gItemIconPalette_LiquidOre[];', 1)
        done.append('externs')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/item_icon_table.h'
    text = open(p).read()
    if f'[{ITEM}]' not in text:
        # before the return-to-field arrow, which is indexed at ITEMS_COUNT and
        # so has to stay last
        anchor = '    // Return to field arrow'
        text = text.replace(anchor, f'    {MARK}\n    [{ITEM}] = '
                            '{gItemIcon_LiquidOre, gItemIconPalette_LiquidOre},\n'
                            + anchor, 1)
        done.append('icon table')
        if not dry:
            open(p, 'w').write(text)

    write_icon(dry)
    return done


# --- the flags this needs -------------------------------------------------
FLAG = 'FLAG_LITTLEROOT_SLIME_TRADED'
HIDE = 'FLAG_HIDE_GRANITE_CAVE_TRADER_STEVEN'
FLAGS = 'include/constants/flags.h'


def add_flags(dry):
    """rename FLAG_UNUSEDs, the way tools/populate.py claims its own.

    The old name stays in the comment so a re-run finds the flag it already
    took instead of walking further down the pool every time, and so the two
    tools cannot end up on the same bit: populate.py only reads lines still
    labelled "Unused Flag", and only hands back the ones carrying its mark.
    """
    p = f'{R.ROOT}/{FLAGS}'
    text = open(p).read()
    done = []
    for name in (FLAG, HIDE):
        if re.search(r'^#define ' + name + r'\s', text, re.M):
            continue
        m = re.search(r'^#define (FLAG_UNUSED_0x[0-9A-Fa-f]+)\s+'
                      r'(0x[0-9A-Fa-f]+) // Unused Flag$', text, re.M)
        if not m:
            sys.exit('no unused flags left')
        pad = ' ' * max(1, 60 - len(name))
        text = text.replace(
            m.group(0), f'#define {name}{pad}{m.group(2)} {MARK} ({m.group(1)})', 1)
        done.append(f'{name} = {m.group(2)} (was {m.group(1)})')
    if done and not dry:
        open(p, 'w').write(text)
    return done


# --- the three trades -----------------------------------------------------
def add_trades(dry):
    done = []
    p = f'{R.ROOT}/include/constants/trade.h'
    text = open(p).read()
    if TRADES[0][0] not in text:
        m = re.search(r'^#define INGAME_TRADE_MEOWTH (\d+)$', text, re.M)
        n = int(m.group(1))
        add = '\n'.join(f'#define {c} {n + 1 + k}'
                        for k, (c, _, _) in enumerate(TRADES))
        text = text.replace(m.group(0), m.group(0) + f'\n{MARK}\n' + add, 1)
        done.append(f'{len(TRADES)} trade ids from {n + 1}')
        if not dry:
            open(p, 'w').write(text)

    p = f'{R.ROOT}/src/data/trade.h'
    text = open(p).read()
    rows = ''
    for const, starter, _ in TRADES:
        rows += (
            f'    [{const}] =\n'
            f'    {{\n'
            f'        .nickname = _("{NICKNAME}"),\n'
            f'        .species = SPECIES_SLIME,\n'
            f'        .ivs = {{15, 15, 15, 15, 15, 15}},\n'
            f'        .abilityNum = 0,\n'
            f'        .otId = {OT_ID},\n'
            f'        .conditions = {{5, 5, 5, 5, 5}},\n'
            f'        .personality = {PERSONALITY},\n'
            f'        .heldItem = ITEM_NONE,\n'
            f'        .mailNum = -1,\n'
            f'        .otName = _("{OT_NAME}"),\n'
            f'        .otGender = MALE,\n'
            f'        .sheen = 10,\n'
            f'        .requestedSpecies = {starter}\n'
            f'    }},\n')
    i = text.index('static const struct InGameTrade sIngameTrades[]')
    j = text.index('\n};', i)
    # Rewrite the whole generated tail rather than only adding it when absent -
    # a row whose contents change is otherwise left as whatever the first run
    # happened to write, and the tool quietly stops meaning what it says.
    k = text.find(f'    {MARK}\n', i, j)
    if k >= 0:
        text = text[:k] + f'    {MARK}\n' + rows + text[j + 1:]
        done.append('sIngameTrades rows rewritten')
    else:
        # vanilla's last entry has no trailing comma, being last
        text = text[:j] + ',\n' + f'    {MARK}\n' + rows + text[j + 1:]
        done.append('sIngameTrades rows')
    if not dry:
        open(p, 'w').write(text)
    return done


# --- the two of them ------------------------------------------------------
NAME = TRADER_MAP        # the trader's map; Steven has his own now


def text(S, name, label, *lines):
    S.append(f'{name}_Text_{label}:')
    for i, l in enumerate(lines):
        S.append(f'\t.string "{l}{"$" if i == len(lines) - 1 else ""}"')
    S.append('')


def trader_scripts():
    """the man in Littleroot who will not say."""
    S = [SMARK, '']
    # VAR_0x8008 is which of the three trades, and it has to be set before
    # GetInGameTradeSpeciesInfo, which reads it through VAR_0x8004.
    S += [f'{NAME}_EventScript_SlimeTrader::',
          '\tlock',
          '\tfaceplayer',
          f'\tgoto_if_unset FLAG_SYS_POKEMON_GET, {NAME}_EventScript_SlimeTraderNoMon',
          f'\tgoto_if_set {FLAG}, {NAME}_EventScript_SlimeTraderDone',
          f'\tcall {NAME}_EventScript_SlimeTraderPick',
          '\tcopyvar VAR_0x8004, VAR_0x8008',
          '\tspecialvar VAR_RESULT, GetInGameTradeSpeciesInfo',
          '\tcopyvar VAR_0x8009, VAR_RESULT',
          f'\tmsgbox {NAME}_Text_SlimeTraderOffer, MSGBOX_YESNO',
          f'\tgoto_if_eq VAR_RESULT, NO, {NAME}_EventScript_SlimeTraderDecline',
          '\tspecial ChoosePartyMon',
          '\tcopyvar VAR_0x800A, VAR_0x8004',
          f'\tgoto_if_eq VAR_0x8004, PARTY_NOTHING_CHOSEN, {NAME}_EventScript_SlimeTraderDecline',
          '\tcopyvar VAR_0x8005, VAR_0x800A',
          '\tspecialvar VAR_RESULT, GetTradeSpecies',
          f'\tgoto_if_ne VAR_RESULT, VAR_0x8009, {NAME}_EventScript_SlimeTraderWrongMon',
          '\tcopyvar VAR_0x8004, VAR_0x8008',
          '\tcopyvar VAR_0x8005, VAR_0x800A',
          '\tspecial CreateInGameTradePokemon',
          '\tspecial DoInGameTradeScene',
          f'\tmsgbox {NAME}_Text_SlimeTraderAfter, MSGBOX_DEFAULT',
          f'\tsetflag {FLAG}',
          '\trelease',
          '\tend',
          '']
    S += [f'{NAME}_EventScript_SlimeTraderPick::']
    for const, _, val in TRADES:
        S.append(f'\tgoto_if_eq VAR_STARTER_MON, {val}, '
                 f'{NAME}_EventScript_SlimeTraderPick{val}')
    S += ['\tsetvar VAR_0x8008, ' + TRADES[0][0], '\treturn', '']
    for const, _, val in TRADES:
        S += [f'{NAME}_EventScript_SlimeTraderPick{val}::',
              f'\tsetvar VAR_0x8008, {const}', '\treturn', '']

    for label in ('NoMon', 'Decline', 'Done'):
        S += [f'{NAME}_EventScript_SlimeTrader{label}::',
              f'\tmsgbox {NAME}_Text_SlimeTrader{label}, MSGBOX_DEFAULT',
              '\trelease', '\tend', '']
    S += [f'{NAME}_EventScript_SlimeTraderWrongMon::',
          '\tbufferspeciesname STR_VAR_1, VAR_0x8009',
          f'\tmsgbox {NAME}_Text_SlimeTraderWrongMon, MSGBOX_DEFAULT',
          '\trelease', '\tend', '']

    # Nothing below names what is on offer, and nothing buffers STR_VAR_2.
    text(S, NAME, 'SlimeTraderOffer',
         'I have something here I am willing\\n',
         'to part with.\\p',
         'What is it? Ah. I would rather not\\n',
         'say. It is easier if you simply see.\\p',
         'Your {STR_VAR_1}, then, for mine.\\n',
         'Do we have an arrangement?')
    text(S, NAME, 'SlimeTraderAfter',
         'There. No refunds, no returns, and\\n',
         'no explanations.\\p',
         'Feed it. It does eat.')
    text(S, NAME, 'SlimeTraderNoMon',
         'You have nothing to trade with, and\\n',
         'I have nothing to say to you.')
    text(S, NAME, 'SlimeTraderDecline',
         'A shame. It will keep.')
    text(S, NAME, 'SlimeTraderWrongMon',
         'No. Your {STR_VAR_1}, or nothing.\\n',
         'I am particular.')
    text(S, NAME, 'SlimeTraderDone',
         'We are square, you and I.\\p',
         'How is it settling in?')
    S.append(SMARK_END)
    return S


def steven_scripts():
    """Steven, once the letter is delivered and he has stopped leaving."""
    M = STEVEN_MAP
    S = [SMARK, '']
    # Which of the two Stevens the room has. Vanilla never sets its own hide
    # flag, so without this the man who wanted the letter is back on the tile
    # the moment you re-enter, standing inside the one who wants the ore.
    S += [f'{M}_EventScript_OpenHoennStevenSetup::',
          f'\tgoto_if_set FLAG_DELIVERED_STEVEN_LETTER, '
          f'{M}_EventScript_OpenHoennStevenSwap',
          f'\tclearflag FLAG_HIDE_GRANITE_CAVE_STEVEN',
          f'\tsetflag {HIDE}',
          '\treturn',
          '',
          f'{M}_EventScript_OpenHoennStevenSwap::',
          '\tsetflag FLAG_HIDE_GRANITE_CAVE_STEVEN',
          f'\tclearflag {HIDE}',
          '\treturn',
          '']
    # Repeatable: one ore in, one METAL SLIME out, as often as you like,
    # because the ore is what is rare and not the trade.
    S += [f'{M}_EventScript_OreSteven::',
          '\tlock',
          '\tfaceplayer',
          f'\tcheckitem {ITEM}, 1',
          f'\tgoto_if_eq VAR_RESULT, FALSE, {M}_EventScript_StevenNoOre',
          f'\tmsgbox {M}_Text_StevenOffer, MSGBOX_YESNO',
          f'\tgoto_if_eq VAR_RESULT, NO, {M}_EventScript_StevenDecline',
          '\tgetpartysize',
          f'\tgoto_if_eq VAR_RESULT, PARTY_SIZE, {M}_EventScript_StevenPartyFull',
          f'\tremoveitem {ITEM}, 1',
          '\tgivemon SPECIES_METAL_SLIME, 1, ITEM_NONE',
          '\tplayfanfare MUS_OBTAIN_ITEM',
          '\twaitfanfare',
          f'\tmsgbox {M}_Text_StevenAfter, MSGBOX_DEFAULT',
          '\trelease', '\tend', '']
    for label in ('NoOre', 'Decline', 'PartyFull'):
        S += [f'{M}_EventScript_Steven{label}::',
              f'\tmsgbox {M}_Text_Steven{label}, MSGBOX_DEFAULT',
              '\trelease', '\tend', '']

    text(S, M, 'StevenOffer',
         'That ore in your bag - may I see it?\\p',
         'Extraordinary. It has a shine no\\n',
         'mineral of this region should have,\\l',
         'and it is warm, which stone is not.\\p',
         'I would very much like it. In return,\\n',
         'a POKéMON I found in the same seam.\\p',
         'Would you trade?')
    text(S, M, 'StevenAfter',
         'Take good care of it. It is young.\\p',
         'Curious, is it not, that the ore and\\n',
         'the POKéMON weigh exactly the same?\\p',
         'I have been trying not to think\\n',
         'about that.')
    text(S, M, 'StevenNoOre',
         'I came back down for the rock, not\\n',
         'for the quiet.\\p',
         'There is an ore in the far corners\\n',
         'of the newer routes - heavy, bright,\\l',
         'and it will not sit still.\\p',
         'Bring me one and I will make it\\n',
         'worth the walk.')
    text(S, M, 'StevenDecline',
         'Of course. Think it over.')
    text(S, M, 'StevenPartyFull',
         'Your team is full. I would rather it\\n',
         'went straight into your care.')
    S.append(SMARK_END)
    return S


def splice(path, body, before=None):
    """put a generated block in a map's scripts.inc, replacing the last one."""
    src = open(path).read()
    if SMARK in src:
        src = src[:src.index(SMARK)] + src[src.index(SMARK_END) + len(SMARK_END):]
    if before and before in src:
        i = src.index(before)
        return src[:i] + body + '\n' + src[i:]
    return src.rstrip('\n') + '\n\n' + body


def obj(x, y, gfx, script, flag='0', move='MOVEMENT_TYPE_FACE_DOWN'):
    return {'graphics_id': gfx, 'x': x, 'y': y, 'elevation': 3,
            'movement_type': move,
            'movement_range_x': 0, 'movement_range_y': 0,
            'trainer_type': 'TRAINER_TYPE_NONE',
            'trainer_sight_or_berry_tree_id': '0',
            'script': script, 'flag': flag}


def put_objects(path, mine, add, dry):
    import json
    d = json.load(open(path))
    d['object_events'] = [o for o in d['object_events']
                          if o['script'] not in mine] + add
    if not dry:
        json.dump(d, open(path, 'w'), indent=2)


def add_npcs(dry):
    done = []

    # Littleroot: the trader, ahead of the gate block that tools/newmaps.py
    # cuts at its own marker and rewrites
    p = f'{R.ROOT}/data/maps/{NAME}/scripts.inc'
    src = splice(p, '\n'.join(trader_scripts()) + '\n',
                 '@ --- open hoenn: gates generated by tools/newmaps.py ---')
    if not dry:
        open(p, 'w').write(src)
    put_objects(f'{R.ROOT}/data/maps/{NAME}/map.json',
                {f'{NAME}_EventScript_SlimeTrader',
                 f'{NAME}_EventScript_Steven'},
                [obj(*TRADER_AT, 'OBJ_EVENT_GFX_MAN_3',
                     f'{NAME}_EventScript_SlimeTrader')], dry)
    done.append(f'the trader in Littleroot at {TRADER_AT}')

    # Granite Cave: Steven, plus the on-transition script that decides which
    # of the two Stevens the room is holding
    M = STEVEN_MAP
    p = f'{R.ROOT}/data/maps/{M}/scripts.inc'
    src = splice(p, '\n'.join(steven_scripts()) + '\n')
    src = '\n'.join(l for l in src.split('\n') if HOOK not in l)
    table = f'{M}_MapScripts::'
    i = src.index(table) + len(table) + 1
    if f'{M}_OnTransition' not in src[:i + 200]:
        src = (src[:i] + f'\tmap_script MAP_SCRIPT_ON_TRANSITION, '
               f'{M}_OnTransition\t{HOOK}\n' + src[i:])
        j = src.index('\t.byte 0\n', i) + len('\t.byte 0\n')
        src = (src[:j] + f'\n{M}_OnTransition:\t{HOOK}\n'
               f'\tcall {M}_EventScript_OpenHoennStevenSetup\t{HOOK}\n'
               f'\tend\t{HOOK}\n' + src[j:])
    if not dry:
        open(p, 'w').write(src)
    put_objects(f'{R.ROOT}/data/maps/{M}/map.json',
                {f'{M}_EventScript_OreSteven'},
                [obj(*STEVEN_AT, 'OBJ_EVENT_GFX_STEVEN',
                     f'{M}_EventScript_OreSteven', HIDE,
                     'MOVEMENT_TYPE_LOOK_AROUND')], dry)
    done.append(f'Steven in {M} at {STEVEN_AT}, hidden by {HIDE}')
    return done


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--dry-run', action='store_true')
    a = ap.parse_args()

    for what in (add_item(a.dry_run), add_flags(a.dry_run),
                 add_trades(a.dry_run), add_npcs(a.dry_run)):
        for line in what:
            print(f'  + {line}')

    if a.check:
        bad = check()
        if bad:
            sys.exit('\n'.join(bad))
        print('checks pass')


def check():
    import json, struct
    bad = []
    items = open(f'{R.ROOT}/include/constants/items.h').read()
    m = re.search(r'^#define ' + ITEM + r'\s+(\d+)$', items, re.M)
    n = re.search(r'^#define ITEMS_COUNT (\d+)$', items, re.M)
    if not m or not n:
        bad.append('item constant or ITEMS_COUNT missing')
    elif int(n.group(1)) != int(m.group(1)) + 1:
        bad.append(f'ITEMS_COUNT {n.group(1)} does not follow {ITEM} {m.group(1)}')
    tbl = open(f'{R.ROOT}/src/data/item_icon_table.h').read()
    if f'[{ITEM}]' not in tbl:
        bad.append('no icon table entry')
    if tbl.index(f'[{ITEM}]') > tbl.index('[ITEMS_COUNT]'):
        bad.append('icon entry is after the return-to-field arrow')
    for p in (ICON, PAL):
        if not os.path.exists(f'{R.ROOT}/{p}'):
            bad.append(f'{p} not written')
    if os.path.exists(f'{R.ROOT}/{ICON}'):
        from PIL import Image
        im = Image.open(f'{R.ROOT}/{ICON}')
        if im.size != (24, 24) or im.mode != 'P':
            bad.append(f'icon is {im.size} {im.mode}, want (24, 24) P')
        pal = open(f'{R.ROOT}/{PAL}').read().split('\n')
        want = [tuple(int(v) for v in l.split()) for l in pal[3:19]]
        got = im.getpalette()[:48]
        for i in range(16):
            if want[i] != tuple(got[i*3:i*3+3]):
                bad.append(f'icon palette {i} is {got[i*3:i*3+3]}, .pal says {want[i]}')
                break

    trades = open(f'{R.ROOT}/src/data/trade.h').read()
    for const, starter, _ in TRADES:
        i = trades.find(f'[{const}] =')
        if i < 0:
            bad.append(f'{const} has no row')
            continue
        blk = trades[i:trades.index('\n    },', i)]
        if f'.requestedSpecies = {starter}' not in blk:
            bad.append(f'{const} does not ask for {starter}')
        if '.species = SPECIES_SLIME' not in blk:
            bad.append(f'{const} does not offer SPECIES_SLIME')
        pid = int(re.search(r'\.personality = (\w+)', blk).group(1), 0)
        oid = int(re.search(r'\.otId = (\d+)', blk).group(1))
        if pid % 25 not in NEUTRAL:
            bad.append(f'{const} personality {pid} gives nature {pid % 25}, '
                       'which is not one of the five that change nothing')
        # GET_SHINY_VALUE(otId, personality), which for a fixed pair is decided
        # here rather than at catch time
        sv = ((oid >> 16) ^ (oid & 0xFFFF) ^ (pid >> 16) ^ (pid & 0xFFFF))
        if sv < 8:
            bad.append(f'{const} is shiny (value {sv}), which was not asked for')
        if f'.nickname = _("{NICKNAME}")' not in blk:
            bad.append(f'{const} is not nicknamed {NICKNAME}')
        if f'.otName = _("{OT_NAME}")' not in blk:
            bad.append(f'{const} does not come from {OT_NAME}')

    # The secret: nothing the trader says may name what is on offer, and
    # nothing may buffer STR_VAR_2, which GetInGameTradeSpeciesInfo fills with
    # the offered species' name. Label names are allowed to say SLIME; only the
    # .string lines matter, because only those reach the player.
    src = open(f'{R.ROOT}/data/maps/{NAME}/scripts.inc').read()
    blk = src[src.index(SMARK):src.index(SMARK_END)]
    said = '\n'.join(re.findall(r'^\t\.string "(.*)"$', blk, re.M))
    for leak in ('STR_VAR_2', 'SLIME', 'Slime', 'slime'):
        if leak in said:
            bad.append(f"the trader says {leak!r}, which gives it away")
    if FLAG not in blk:
        bad.append('the trade is not flagged, so it would repeat')

    # Steven's room: the two of them are mutually exclusive, so exactly one
    # object may be visible for any value of FLAG_DELIVERED_STEVEN_LETTER
    src = open(f'{R.ROOT}/data/maps/{STEVEN_MAP}/scripts.inc').read()
    if f'{STEVEN_MAP}_OnTransition' not in src:
        bad.append(f'{STEVEN_MAP} has no on-transition script to swap them')
    swap = src[src.index(SMARK):src.index(SMARK_END)]
    for want in (f'setflag {HIDE}', f'clearflag {HIDE}',
                 'setflag FLAG_HIDE_GRANITE_CAVE_STEVEN',
                 'clearflag FLAG_HIDE_GRANITE_CAVE_STEVEN'):
        if want not in swap:
            bad.append(f'the swap never does "{want}"')
    d = json.load(open(f'{R.ROOT}/data/maps/{STEVEN_MAP}/map.json'))
    byflag = {o.get('flag'): o for o in d['object_events']}
    if HIDE not in byflag:
        bad.append(f'no object in {STEVEN_MAP} is hidden by {HIDE}')
    if 'FLAG_HIDE_GRANITE_CAVE_STEVEN' not in byflag:
        bad.append('vanilla Steven lost his hide flag')
    if (HIDE in byflag and 'FLAG_HIDE_GRANITE_CAVE_STEVEN' in byflag
            and (byflag[HIDE]['x'], byflag[HIDE]['y'])
            != (byflag['FLAG_HIDE_GRANITE_CAVE_STEVEN']['x'],
                byflag['FLAG_HIDE_GRANITE_CAVE_STEVEN']['y'])):
        bad.append('the two Stevens do not stand on the same tile')

    # both of them stand somewhere real, and neither blocks the only way past
    lay, maps, _ = R.solve()
    for const, mapdir, spots in (
            ('MAP_LITTLEROOT_TOWN', NAME, [TRADER_AT]),
            ('MAP_GRANITE_CAVE_STEVENS_ROOM', STEVEN_MAP, [STEVEN_AT])):
        d = json.load(open(f'{R.ROOT}/data/maps/{mapdir}/map.json'))
        L = lay[maps[const]['layout']]
        w, h = L['width'], L['height']
        raw = struct.unpack(
            f'<{w*h}H',
            open(f'{R.ROOT}/{L["blockdata_filepath"]}', 'rb').read()[:w*h*2])
        walk = [((v >> 10) & 3) == 0 for v in raw]
        ele = [(v >> 12) & 0xF for v in raw]
        solid = {(o['x'], o['y']) for o in d['object_events']}
        for x, y in spots:
            if not walk[y*w + x]:
                bad.append(f'{const} ({x},{y}) is not somewhere a person '
                           'can stand')
        # with every sprite treated as a wall, can the player still get
        # everywhere? An NPC in a one-cell gap shuts whatever is behind it
        ok = lambda a, b: a == b or 0 in (a, b) or 15 in (a, b)
        free = [i for i in range(w*h) if walk[i] and (i % w, i // w) not in solid]
        if not free:
            continue
        seen, q = {free[0]}, [free[0]]
        while q:
            i = q.pop()
            x, y = i % w, i // w
            for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
                j = ny*w + nx
                if (0 <= nx < w and 0 <= ny < h and j not in seen and walk[j]
                        and (nx, ny) not in solid and ok(ele[i], ele[j])):
                    seen.add(j)
                    q.append(j)
        if len(free) - len(seen):
            bad.append(f'{len(free) - len(seen)} cells of {const} are cut off '
                       'by a sprite')
    return bad


if __name__ == '__main__':
    sys.exit(main())
