Route139_MapScripts::
	.byte 0

// Open Hoenn - tools/trainers.py

Route139_EventScript_Fiona::
	trainerbattle_single TRAINER_FIONA, Route139_Text_FionaIntro, Route139_Text_FionaDefeat
	msgbox Route139_Text_FionaPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_FionaIntro:
	.string "A short battle, before the light\ngoes.$"

Route139_Text_FionaDefeat:
	.string "Well grown.$"

Route139_Text_FionaPostBattle:
	.string "Safe travels.$"

Route139_EventScript_Derwent::
	trainerbattle_single TRAINER_DERWENT, Route139_Text_DerwentIntro, Route139_Text_DerwentDefeat
	msgbox Route139_Text_DerwentPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DerwentIntro:
	.string "Not many come this far. Battle me.$"

Route139_Text_DerwentDefeat:
	.string "You've come a long way indeed.$"

Route139_Text_DerwentPostBattle:
	.string "Keep heading on. It opens out.$"

Route139_EventScript_Darby::
	trainerbattle_single TRAINER_DARBY, Route139_Text_DarbyIntro, Route139_Text_DarbyDefeat
	msgbox Route139_Text_DarbyPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DarbyIntro:
	.string "A challenger! At last.$"

Route139_Text_DarbyDefeat:
	.string "The ROUTE is yours.$"

Route139_Text_DarbyPostBattle:
	.string "There's more of us further along.$"

Route139_EventScript_Dennis::
	trainerbattle_single TRAINER_DENNIS, Route139_Text_DennisIntro, Route139_Text_DennisDefeat
	msgbox Route139_Text_DennisPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DennisIntro:
	.string "I've been waiting for someone like\nyou.$"

Route139_Text_DennisDefeat:
	.string "Beaten.$"

Route139_Text_DennisPostBattle:
	.string "Rest before the next stretch.$"

Route139_EventScript_Desmond::
	trainerbattle_single TRAINER_DESMOND, Route139_Text_DesmondIntro, Route139_Text_DesmondDefeat
	msgbox Route139_Text_DesmondPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DesmondIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route139_Text_DesmondDefeat:
	.string "Well fought.$"

Route139_Text_DesmondPostBattle:
	.string "Good luck out there.$"

Route139_EventScript_Dexter::
	trainerbattle_single TRAINER_DEXTER, Route139_Text_DexterIntro, Route139_Text_DexterDefeat
	msgbox Route139_Text_DexterPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DexterIntro:
	.string "You've come a long way. Let's see\nwhy.$"

Route139_Text_DexterDefeat:
	.string "I underestimated you.$"

Route139_Text_DexterPostBattle:
	.string "I'll be training when you come\nback.$"

Route139_EventScript_Flora::
	trainerbattle_single TRAINER_FLORA, Route139_Text_FloraIntro, Route139_Text_FloraDefeat
	msgbox Route139_Text_FloraPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_FloraIntro:
	.string "t$"

Route139_Text_FloraDefeat:
	.string "t$"

Route139_Text_FloraPostBattle:
	.string "$"

Route139_EventScript_Gwendolen::
	trainerbattle_single TRAINER_GWENDOLEN, Route139_Text_GwendolenIntro, Route139_Text_GwendolenDefeat
	msgbox Route139_Text_GwendolenPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_GwendolenIntro:
	.string "h$"

Route139_Text_GwendolenDefeat:
	.string "$"

Route139_Text_GwendolenPostBattle:
	.string "w$"

Route139_EventScript_Gilda::
	trainerbattle_single TRAINER_GILDA, Route139_Text_GildaIntro, Route139_Text_GildaDefeat
	msgbox Route139_Text_GildaPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_GildaIntro:
	.string "A challenger! At last.$"

Route139_Text_GildaDefeat:
	.string "The ROUTE is yours.$"

Route139_Text_GildaPostBattle:
	.string "There's more of us further along.$"

Route139_EventScript_Griselda::
	trainerbattle_single TRAINER_GRISELDA, Route139_Text_GriseldaIntro, Route139_Text_GriseldaDefeat
	msgbox Route139_Text_GriseldaPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_GriseldaIntro:
	.string "I've been waiting for someone like\nyou.$"

Route139_Text_GriseldaDefeat:
	.string "Beaten.$"

Route139_Text_GriseldaPostBattle:
	.string "Rest before the next stretch.$"

Route139_EventScript_Harriet::
	trainerbattle_single TRAINER_HARRIET, Route139_Text_HarrietIntro, Route139_Text_HarrietDefeat
	msgbox Route139_Text_HarrietPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_HarrietIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route139_Text_HarrietDefeat:
	.string "Well fought.$"

Route139_Text_HarrietPostBattle:
	.string "Good luck out there.$"

Route139_EventScript_Driscoll::
	trainerbattle_single TRAINER_DRISCOLL, Route139_Text_DriscollIntro, Route139_Text_DriscollDefeat
	msgbox Route139_Text_DriscollPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DriscollIntro:
	.string "You've come a long way. Let's see\nwhy.$"

Route139_Text_DriscollDefeat:
	.string "I underestimated you.$"

Route139_Text_DriscollPostBattle:
	.string "I'll be training when you come\nback.$"

Route139_EventScript_Dustin::
	trainerbattle_single TRAINER_DUSTIN, Route139_Text_DustinIntro, Route139_Text_DustinDefeat
	msgbox Route139_Text_DustinPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_DustinIntro:
	.string "Battle me and I'll let you pass.$"

Route139_Text_DustinDefeat:
	.string "That settles it.$"

Route139_Text_DustinPostBattle:
	.string "Safe travels.$"

Route139_EventScript_Hazel::
	trainerbattle_single TRAINER_HAZEL, Route139_Text_HazelIntro, Route139_Text_HazelDefeat
	msgbox Route139_Text_HazelPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_HazelIntro:
	.string "Not many come this far. Battle me.$"

Route139_Text_HazelDefeat:
	.string "You've come a long way indeed.$"

Route139_Text_HazelPostBattle:
	.string "Keep heading on. It opens out.$"

Route139_EventScript_Earl::
	trainerbattle_single TRAINER_EARL, Route139_Text_EarlIntro, Route139_Text_EarlDefeat
	msgbox Route139_Text_EarlPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_EarlIntro:
	.string "A challenger! At last.$"

Route139_Text_EarlDefeat:
	.string "The ROUTE is yours.$"

Route139_Text_EarlPostBattle:
	.string "There's more of us further along.$"

Route139_EventScript_Eldon::
	trainerbattle_single TRAINER_ELDON, Route139_Text_EldonIntro, Route139_Text_EldonDefeat
	msgbox Route139_Text_EldonPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_EldonIntro:
	.string "I've been waiting for someone like\nyou.$"

Route139_Text_EldonDefeat:
	.string "Beaten.$"

Route139_Text_EldonPostBattle:
	.string "Rest before the next stretch.$"

Route139_EventScript_Imogen::
	trainerbattle_single TRAINER_IMOGEN, Route139_Text_ImogenIntro, Route139_Text_ImogenDefeat
	msgbox Route139_Text_ImogenPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_ImogenIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route139_Text_ImogenDefeat:
	.string "Well fought.$"

Route139_Text_ImogenPostBattle:
	.string "Good luck out there.$"

Route139_EventScript_Ingrid::
	trainerbattle_single TRAINER_INGRID, Route139_Text_IngridIntro, Route139_Text_IngridDefeat
	msgbox Route139_Text_IngridPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_IngridIntro:
	.string "You've come a long way. Let's see\nwhy.$"

Route139_Text_IngridDefeat:
	.string "I underestimated you.$"

Route139_Text_IngridPostBattle:
	.string "I'll be training when you come\nback.$"

Route139_EventScript_Iris::
	trainerbattle_single TRAINER_IRIS, Route139_Text_IrisIntro, Route139_Text_IrisDefeat
	msgbox Route139_Text_IrisPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_IrisIntro:
	.string "Battle me and I'll let you pass.$"

Route139_Text_IrisDefeat:
	.string "That settles it.$"

Route139_Text_IrisPostBattle:
	.string "Safe travels.$"

Route139_EventScript_Elias::
	trainerbattle_single TRAINER_ELIAS, Route139_Text_EliasIntro, Route139_Text_EliasDefeat
	msgbox Route139_Text_EliasPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_EliasIntro:
	.string "e$"

Route139_Text_EliasDefeat:
	.string "c$"

Route139_Text_EliasPostBattle:
	.string "e$"

Route139_EventScript_Isolde::
	trainerbattle_single TRAINER_ISOLDE, Route139_Text_IsoldeIntro, Route139_Text_IsoldeDefeat
	msgbox Route139_Text_IsoldePostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_IsoldeIntro:
	.string "A challenger! At last.$"

Route139_Text_IsoldeDefeat:
	.string "The ROUTE is yours.$"

Route139_Text_IsoldePostBattle:
	.string "There's more of us further along.$"

Route139_EventScript_Emmet::
	trainerbattle_single TRAINER_EMMET, Route139_Text_EmmetIntro, Route139_Text_EmmetDefeat
	msgbox Route139_Text_EmmetPostBattle, MSGBOX_AUTOCLOSE
	end

Route139_Text_EmmetIntro:
	.string "I've been waiting for someone like\nyou.$"

Route139_Text_EmmetDefeat:
	.string "Beaten.$"

Route139_Text_EmmetPostBattle:
	.string "Rest before the next stretch.$"

