Route143_MapScripts::
	.byte 0

// Open Hoenn - tools/trainers.py

Route143_EventScript_Horace::
	trainerbattle_single TRAINER_HORACE, Route143_Text_HoraceIntro, Route143_Text_HoraceDefeat
	msgbox Route143_Text_HoracePostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_HoraceIntro:
	.string "Battle me and I'll let you pass.$"

Route143_Text_HoraceDefeat:
	.string "That settles it.$"

Route143_Text_HoracePostBattle:
	.string "Safe travels.$"

Route143_EventScript_Hugo::
	trainerbattle_single TRAINER_HUGO, Route143_Text_HugoIntro, Route143_Text_HugoDefeat
	msgbox Route143_Text_HugoPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_HugoIntro:
	.string "Not many come this far. Battle me.$"

Route143_Text_HugoDefeat:
	.string "You've come a long way indeed.$"

Route143_Text_HugoPostBattle:
	.string "Keep heading on. It opens out.$"

Route143_EventScript_Idris::
	trainerbattle_single TRAINER_IDRIS, Route143_Text_IdrisIntro, Route143_Text_IdrisDefeat
	msgbox Route143_Text_IdrisPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_IdrisIntro:
	.string "A challenger! At last.$"

Route143_Text_IdrisDefeat:
	.string "The ROUTE is yours.$"

Route143_Text_IdrisPostBattle:
	.string "There's more of us further along.$"

Route143_EventScript_Imogen::
	trainerbattle_single TRAINER_IMOGEN, Route143_Text_ImogenIntro, Route143_Text_ImogenDefeat
	msgbox Route143_Text_ImogenPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_ImogenIntro:
	.string "You've walked a long way. Sit!\n...After.$"

Route143_Text_ImogenDefeat:
	.string "Beaten before dessert.$"

Route143_Text_ImogenPostBattle:
	.string "Rest before the next stretch.$"

Route143_EventScript_Ingrid::
	trainerbattle_single TRAINER_INGRID, Route143_Text_IngridIntro, Route143_Text_IngridDefeat
	msgbox Route143_Text_IngridPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_IngridIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route143_Text_IngridDefeat:
	.string "Well fought.$"

Route143_Text_IngridPostBattle:
	.string "Good luck out there.$"

Route143_EventScript_Iris::
	trainerbattle_single TRAINER_IRIS, Route143_Text_IrisIntro, Route143_Text_IrisDefeat
	msgbox Route143_Text_IrisPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_IrisIntro:
	.string "Your stance is wrong. Your team may\nnot be.$"

Route143_Text_IrisDefeat:
	.string "A worthy match.$"

Route143_Text_IrisPostBattle:
	.string "I'll be training when you come\nback.$"

Route143_EventScript_Isolde::
	trainerbattle_single TRAINER_ISOLDE, Route143_Text_IsoldeIntro, Route143_Text_IsoldeDefeat
	msgbox Route143_Text_IsoldePostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_IsoldeIntro:
	.string "Battle me and I'll let you pass.$"

Route143_Text_IsoldeDefeat:
	.string "That settles it.$"

Route143_Text_IsoldePostBattle:
	.string "Safe travels.$"

Route143_EventScript_Ivor::
	trainerbattle_single TRAINER_IVOR, Route143_Text_IvorIntro, Route143_Text_IvorDefeat
	msgbox Route143_Text_IvorPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_IvorIntro:
	.string "Not many come this far. Battle me.$"

Route143_Text_IvorDefeat:
	.string "You've come a long way indeed.$"

Route143_Text_IvorPostBattle:
	.string "Keep heading on. It opens out.$"

Route143_EventScript_Jamie::
	trainerbattle_single TRAINER_JAMIE, Route143_Text_JamieIntro, Route143_Text_JamieDefeat
	msgbox Route143_Text_JamiePostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JamieIntro:
	.string "A challenger! At last.$"

Route143_Text_JamieDefeat:
	.string "The ROUTE is yours.$"

Route143_Text_JamiePostBattle:
	.string "There's more of us further along.$"

Route143_EventScript_Jasper::
	trainerbattle_single TRAINER_JASPER, Route143_Text_JasperIntro, Route143_Text_JasperDefeat
	msgbox Route143_Text_JasperPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JasperIntro:
	.string ".$"

Route143_Text_JasperDefeat:
	.string "$"

Route143_Text_JasperPostBattle:
	.string "e$"

Route143_EventScript_Jemma::
	trainerbattle_single TRAINER_JEMMA, Route143_Text_JemmaIntro, Route143_Text_JemmaDefeat
	msgbox Route143_Text_JemmaPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JemmaIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route143_Text_JemmaDefeat:
	.string "Well fought.$"

Route143_Text_JemmaPostBattle:
	.string "Good luck out there.$"

Route143_EventScript_Jethro::
	trainerbattle_single TRAINER_JETHRO, Route143_Text_JethroIntro, Route143_Text_JethroDefeat
	msgbox Route143_Text_JethroPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JethroIntro:
	.string "You've come a long way. Let's see\nwhy.$"

Route143_Text_JethroDefeat:
	.string "I underestimated you.$"

Route143_Text_JethroPostBattle:
	.string "I'll be training when you come\nback.$"

Route143_EventScript_Julian::
	trainerbattle_single TRAINER_JULIAN, Route143_Text_JulianIntro, Route143_Text_JulianDefeat
	msgbox Route143_Text_JulianPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JulianIntro:
	.string "Battle me and I'll let you pass.$"

Route143_Text_JulianDefeat:
	.string "That settles it.$"

Route143_Text_JulianPostBattle:
	.string "Safe travels.$"

Route143_EventScript_Josie::
	trainerbattle_single TRAINER_JOSIE, Route143_Text_JosieIntro, Route143_Text_JosieDefeat
	msgbox Route143_Text_JosiePostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JosieIntro:
	.string "Not many come this far. Battle me.$"

Route143_Text_JosieDefeat:
	.string "You've come a long way indeed.$"

Route143_Text_JosiePostBattle:
	.string "Keep heading on. It opens out.$"

Route143_EventScript_Jude::
	trainerbattle_single TRAINER_JUDE, Route143_Text_JudeIntro, Route143_Text_JudeDefeat
	msgbox Route143_Text_JudePostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JudeIntro:
	.string "A challenger! At last.$"

Route143_Text_JudeDefeat:
	.string "The ROUTE is yours.$"

Route143_Text_JudePostBattle:
	.string "There's more of us further along.$"

Route143_EventScript_Juno::
	trainerbattle_single TRAINER_JUNO, Route143_Text_JunoIntro, Route143_Text_JunoDefeat
	msgbox Route143_Text_JunoPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_JunoIntro:
	.string "I've been waiting for someone like\nyou.$"

Route143_Text_JunoDefeat:
	.string "Beaten.$"

Route143_Text_JunoPostBattle:
	.string "Rest before the next stretch.$"

Route143_EventScript_Keaton::
	trainerbattle_single TRAINER_KEATON, Route143_Text_KeatonIntro, Route143_Text_KeatonDefeat
	msgbox Route143_Text_KeatonPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_KeatonIntro:
	.string "Stop there. This ROUTE is mine to\ndefend.$"

Route143_Text_KeatonDefeat:
	.string "Well fought.$"

Route143_Text_KeatonPostBattle:
	.string "Good luck out there.$"

Route143_EventScript_Kendra::
	trainerbattle_single TRAINER_KENDRA, Route143_Text_KendraIntro, Route143_Text_KendraDefeat
	msgbox Route143_Text_KendraPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_KendraIntro:
	.string "You've come a long way. Let's see\nwhy.$"

Route143_Text_KendraDefeat:
	.string "I underestimated you.$"

Route143_Text_KendraPostBattle:
	.string "I'll be training when you come\nback.$"

Route143_EventScript_Kestrel::
	trainerbattle_single TRAINER_KESTREL, Route143_Text_KestrelIntro, Route143_Text_KestrelDefeat
	msgbox Route143_Text_KestrelPostBattle, MSGBOX_AUTOCLOSE
	end

Route143_Text_KestrelIntro:
	.string "Battle me and I'll let you pass.$"

Route143_Text_KestrelDefeat:
	.string "That settles it.$"

Route143_Text_KestrelPostBattle:
	.string "Safe travels.$"

